name: changelog
on:
  push:
   tags: 
     - 'a*'
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50
    - uses: notlmn/release-with-changelog@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
